task: detection

model: DEIM
criterion: DEIMCriterion
postprocessor: PostProcessor

use_focal_loss: True
eval_spatial_size: [640, 640]   # 👈 shared fixed size
checkpoint_freq: 4

DEIM:
  backbone: HGNetv2
  encoder: HybridEncoder
  decoder: DFINETransformer

# 🔑 Shared protocol training schedule
lrsheduler: flatcosine
lr_gamma: 1
warmup_iter: 500
flat_epoch: 25       # 👈 half of 50 epochs
no_aug_epoch: 5      # 👈 last 5 epochs w/o aug

HGNetv2:
  pretrained: True
  local_model_dir: /home/rbu/Comparison_Paper_Object_Detection/DEIM_varnan/DEIM/checkpoints/deim_dfine_hgnetv2_x_coco_50e.pth

HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'

  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'

DFINETransformer:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3

  num_layers: 6
  eval_idx: -1
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0

  reg_max: 32
  reg_scale: 4
  layer_scale: 1

  num_points: [3, 6, 3]
  cross_attn_method: default
  query_select_method: default

PostProcessor:
  num_top_queries: 300

DEIMCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5}
  losses: ['vfl', 'boxes', 'local']
  alpha: 0.75
  gamma: 2.0
  reg_max: 32

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0
