__include__: [
  './dfine_hgnetv2_m_seaclear.yml',
  '../base/deim.yml',
  '../base/dataloader.yml'
]

output_dir: ./outputs/deim_hgnetv2_m_seaclear

optimizer:
  type: AdamW
  params: 
    -
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.00004
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001

# Shared protocol schedule
epoches: 200          # max epochs
flat_epoch: 10        # halfway point
no_aug_epoch: 2       # last 2 epochs w/o aug

early_stopping:
  metric: 'mAP'       # validation metric to monitor
  patience: 10        # stop if no improvement for 10 epochs

## DataAug (shared protocol)
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [10, 25, 40]

  collate_fn:
    mixup_epochs: [10, 25]
    stop_epoch: 40