__include__: [
  './dfine_hgnetv2_m_seaclear.yml',
  '../base/deim.yml',
  '../base/dataloader.yml'
]

output_dir: ./outputs/deim_hgnetv2_m_seaclear

optimizer:
  type: AdamW
  params: 
    -
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.00004
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001

# Shared protocol schedule
epoches: 50          # 👈 was 102 → now 50
flat_epoch: 25       # 👈 halfway point
no_aug_epoch: 5      # 👈 last 5 epochs w/o aug

## DataAug (shared protocol)
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [10, 25, 40]   # 👈 scaled down from [4,49,90]

  collate_fn:
    mixup_epochs: [10, 25]   # 👈 scaled down
    stop_epoch: 40           # 👈 sync w/ augment policy
