__include__: [
  '../dataset/custom_detection.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
]

output_dir: ./output/dfine_hgnetv2_m_seaclear

DEIM:
  backbone: HGNetv2

HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

DFINETransformer:
  num_layers: 4
  eval_idx: -1

HybridEncoder:
  in_channels: [384, 768, 1536]
  hidden_dim: 256
  depth_mult: 0.67

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00002
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00002
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001

# Shared protocol schedule
epoches: 50          # 👈 was 132 → now 50
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 40    # 👈 stop aug at 40 (instead of 120)
  collate_fn:
    stop_epoch: 40   # 👈 match augmentation stop
    ema_restart_decay: 0.9999
    base_size_repeat: 3   # 👈 reduced from 6 → fair w/ DEIM
